{
 "title": "page ACCUEIL",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "teams",
    "label": "Teams",
    "query": "select\n\tt.id\nfrom\n\tteam t\nJOIN team_member tm ON\n\tt.id = tm.team_id\nJOIN user u on\n\tu.id = tm.user_id\nWHERE\n\tu.email = '${__user.email}'\n\tAND u.org_id = ${__org}\n\tAND u.is_disabled IS FALSE\n/* TODO should admin users belong to every team? */"
   },
   {
    "name": "view_status",
    "query": "Physique : invalid,Logique : alarmed"
   },
   {
    "name": "allowed_objects",
    "query": "db.permissions.aggregate([\n  {\"$match\": {\"teamId\": {\"$in\": [${teams:raw}]}}},\n  {\"$unwind\": \"$realtimeDataId\"},\n{\"$project\": {\"_id\": \"$realtimeDataId\"}},\n{\"$sort\": {\"_id\": 1}}\n])\n"
   },
   {
    "name": "line",
    "label": "Ligne",
    "query": "Ligne 14 : L14,Ligne 15 : L15,Ligne 16 : L16,Ligne 17 : L17,Ligne 18 : L18,"
   },
   { "name": "protocolSourceConnectionNumber", "query": "1200,8888" },
   {
    "name": "devices",
    "query": "db.realtimeData.aggregate([\n{\n\"$match\": {\n\"location.properties.ligne\": {\"$in\": [${line:doublequote}]},\n\"protocolSourceObjectAddress\": /^[^\\/]+(\\/[^\\/]+){2}$/,\n\"protocolSourceConnectionNumber\": ${protocolSourceConnectionNumber:raw}\n}\n},{\n//\"$project\": {\"_id\" : \"$$ROOT.tag\"}\n\"$project\": {\"__value\" : \"$$ROOT._id\", \"__text\" : \"$$ROOT.description\"}\n},\n{\n$sort: {\"location.properties.code\": 1}\n}\n])"
   },
   {
    "name": "depth",
    "label": "Niveau de zoom",
    "query": "Ligne : 1,Gare : 2,AdV : 3,PMDiagBox : 4"
   },
   {
    "name": "level1",
    "label": "Ligne",
    "query": "db.realtimeData.aggregate([\n{\n\"$match\": {\n\"protocolSourceObjectAddress\": /^[^\\/]+(\\/[^\\/]+){1}$/,\n\"protocolSourceConnectionNumber\": ${protocolSourceConnectionNumber:raw}\n}\n},{\n\"$project\": {\"__value\" : \"$$ROOT._id\", \"__text\" : \"$$ROOT.description\"}\n},\n{\n$sort: {\"location.properties.code\": 1}\n}\n])"
   },
   {
    "name": "level2",
    "label": "Gare",
    "query": "db.realtimeData.aggregate([\n  {\n    \"$match\": {\n        _id: {$in: [${level1:raw}]}\n    }\n  },\n\n{\n  $lookup: {\n    from: \"realtimeData\",\n    localField: \"parcels\",\n    foreignField: \"_id\",\n    as: \"children\"\n  }\n},\n{\n  $unwind: {\n    path: \"$children\",\n  }\n},\n{\n  $replaceRoot: {\n    newRoot: \"$children\",\n  }\n},\n\n{$project: {__text:\"$description\",__value: \"$_id\",}},\n\n])"
   },
   {
    "name": "level3",
    "label": "AdV",
    "query": "db.realtimeData.aggregate([\n  {\n    \"$match\": {\n        _id: {$in: [${level2:raw}]}\n    }\n  },\n\n{\n  $lookup: {\n    from: \"realtimeData\",\n    localField: \"parcels\",\n    foreignField: \"_id\",\n    as: \"children\"\n  }\n},\n{\n  $unwind: {\n    path: \"$children\",\n  }\n},\n{\n  $replaceRoot: {\n    newRoot: \"$children\",\n  }\n},\n\n{$project: {__text:\"$description\",__value: \"$_id\",}},\n\n])"
   },
   {
    "name": "level4",
    "label": "PMDiagBox",
    "query": "db.realtimeData.aggregate([\n  {\n    \"$match\": {\n        _id: {$in: [${level3:raw}]}\n    }\n  },\n\n{\n  $lookup: {\n    from: \"realtimeData\",\n    localField: \"parcels\",\n    foreignField: \"_id\",\n    as: \"children\"\n  }\n},\n{\n  $unwind: {\n    path: \"$children\",\n  }\n},\n{\n  $replaceRoot: {\n    newRoot: \"$children\",\n  }\n},\n\n{$project: {__text:\"$description\",__value: \"$_id\",}},\n\n])"
   },
   {
    "name": "level5",
    "label": "Capteur",
    "query": "db.realtimeData.aggregate([\n  {\n    \"$match\": {\n        _id: {$in: [${level4:raw}]}\n    }\n  },\n\n{\n  $lookup: {\n    from: \"realtimeData\",\n    localField: \"parcels\",\n    foreignField: \"_id\",\n    as: \"children\"\n  }\n},\n{\n  $unwind: {\n    path: \"$children\",\n  }\n},\n{\n  $addFields: { \"children.address\": { $split: [ \"$protocolSourceObjectAddress\", \"/\" ] } }\n},\n{\n  $replaceRoot: {\n    newRoot: \"$children\",\n  }\n},\n\n//{$project: {__text:\"$description\",__value: \"$_id\",}},//\n{$project: {__text: { $concat: [ { $arrayElemAt: [\"$address\", 4]}, \"/\", \"$description\" ] },__value: \"$_id\",}},\n])"
   },
   {
    "name": "courbes",
    "query": "db.realtimeData.aggregate([\n  {\n    \"$match\": {\n        _id: {$in: [${level5:raw}]},\n\ntag:/Curve/,\n    }\n  },\n\n{$project: {__text:\"$description\",__value: \"$_id\",}},\n\n])"
   },
   {
    "name": "indicateurs",
    "query": "db.realtimeData.aggregate([\n  {\n    \"$match\": {\n        _id: {$in: [${level5:raw}]},\n\n$or:[\n{tag:/Indicator/},\n{origin: \"calculated\"}\n]\n    }\n  },\n\n//{$project: {__text:\"$description\",__value: \"$_id\",}},\n{$project: {__text:\"$tag\",__value: \"$_id\",}},\n//{$project: {__text: {$concat: [\"${level2:text}\",\"${level3:text}\",\"${level4:text}\", \"$description\"]},__value: \"$_id\",}},\n//{$project: {__text:\"$ungroupedDescription\",__value: \"$_id\",}},\n\n])"
   },
   {
    "name": "pathPattern",
    "query": "db.realtimeData.aggregate([\n  {$sample: {size: 1}},\n\n  {\n    $addFields: {\n      address: [\"${level1:text}\", \"${level2:text}\", \"${level3:text}\", \"${level4:text}\", \"${level5:text}\"]\n    }\n  },\n\n  {\n    // slice up to the first occurence of keyword 'All'\n    $project: {\n      _id: {\n        $slice: [\n          \"$address\",\n          {$indexOfArray: [\"$address\", \"All\", 0]},\n        ]\n      }\n    },\n  },\n\n  {\n    // no deeper than ${depth}\n    $project: {\n      _id: {\n        $slice: [\n          \"$_id\",\n          ${depth},\n        ]\n      }\n    },\n  },\n\n  {\n    // build the path: concatenate the array with \"/\" as a separator \n    // TODO is there really no \"join\" function in mongo ???\n    $project: {\n      _id: {\n        $reduce: {\n          input: \"$_id\",\n          initialValue: \"\",\n          in: { $concat : [ \"$$value\" ,\"/\", \"$$this\"] }\n        }\n      }\n    }\n  },\n\n  {\n    // remove leading \"/\"\n    $project: {\n      //_id: {$substr: [\"$_id\", 1, {$strLenBytes: \"$_id\"}]}\n      _id: { $replaceOne: {input: \"$_id\", find: \"/\", replacement: \"\"} }\n    }\n  },\n\n\n\n])"
   },
   { "name": "deeper", "query": "select ${depth} +1" },
   { "name": "currentLevel", "query": "select ${'level' || ${depth}}" }
  ]
 },
 "panels": [
  {
   "title": "Évolution des états",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill(\n    INTERVAL '5 min',\n    time_tag_at_source,\n    '${__from:date}',\n    '${__to:date}'\n  ) as time,\n  description AS metric,\n  locf(max(${view_status}), 1)\nFROM\n  hist_view h\n  right outer join realtime_data rd on rd.tag = h.tag\nWHERE\n  protocolSourceConnectionNumber = '${protocolSourceConnectionNumber}'\n  AND $__timeFilter(time_tag_at_source)\n  AND _id IN (\n    select\n      unnest(\n        array [\n          string_to_array(\n            regexp_replace(\n              '${level0:raw},${level1:raw},${level2:raw},${level3:raw},${level4:raw},${level5:raw}', ',+', ',', 'g'\n            ),\n            ','\n          )\n        ]\n      )\n  )\n  \n  AND rd.tag ~ '^[^\\/]+(\\/[^\\/]+){${depth}}$'\nGROUP BY\n  1,\n  2\nORDER BY\n  1,\n  2"
    }
   ]
  },
  {
   "title": "CARTO les ${depth} de ${pathPattern}",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 13, "x": 7, "y": 0 },
   "targets": [
    {
     "target": "db.realtimeData.aggregate([\n{\n  $match: {\n    $and: [\n      {protocolSourceConnectionNumber: $protocolSourceConnectionNumber},\n      {tag: /^[^\\/]+(\\/[^\\/]+){${depth}}$/},\n      {tag: /^[^\\/]+(\\/[^\\/]+){2}$/}, // !!!!!!!!!!!!!!!!!!!!!!!!!!\n      {tag: {$regex: ${pathPattern:doublequote}}},\n    ]\n  }\n},\n{\"$sort\": {\"location.properties.code\": 1}},\n{$addFields: {address: {$split: [\"$protocolSourceObjectAddress\",\"/\"]},}},\n {\n        \"$project\": {\n            \"_id\": 1,\n            \"description\": 1,\n            \"metric\": \"$description\",\n            \"protocolSourceObjectAddressBAK\": 1,\n            \"tag\": 1,\n            \"ungroupedDescription\": 1,\n            \"alarmed\": 1,\n            \"alarmState\": 1,\n            \"alarmRange\": 1,\n            \"invalid\": 1,\n            \"timeTag\": 1,\n            \"timeTagAtSource\": 1,\n            \"code\": \"$location.properties.code\",\n            \"connection\": \"$location.properties.connexion\",\n            \"lines\": \"$location.properties.ligne\",\n            \"longitude\": { \"$arrayElemAt\": [\"$location.geometry.coordinates\", 0] },\n            \"latitude\": { \"$arrayElemAt\": [\"$location.geometry.coordinates\", 1] },\n            \"location\": 1,\n            \"status\": \"$${view_status}\",\n//            \"value\": {$toInt: \"$${view_status}\"},\n\"value\": {$cond: [{$eq: [\"$timeTag\", null]}, null, {$toInt: \"$${view_status}\"}]},\n//address: 1,\nl1: {$arrayElemAt: [\"$address\", 1]},\nl2: {$arrayElemAt: [\"$address\", 2]},\nl3: {$arrayElemAt: [\"$address\", 3]},\nl4: {$arrayElemAt: [\"$address\", 4]},\nl5: {$arrayElemAt: [\"$address\", 5]},\n\n        }\n    }\n])",
     "type": "table"
    },
    {
     "target": "db.realtimeData.aggregate([\n{\n  $match: {\n    $and: [\n      {protocolSourceConnectionNumber: $protocolSourceConnectionNumber},\n      {tag: /^[^\\/]+(\\/[^\\/]+){${depth}}$/},\n      {tag: /^[^\\/]+(\\/[^\\/]+){3}$/}, // !!!!!!!!!!!!!!!!!!!!!!!!!!\n      {tag: {$regex: ${pathPattern:doublequote}}},\n    ]\n  }\n},\n{\"$sort\": {\"location.properties.code\": 1}},\n{$addFields: {address: {$split: [\"$protocolSourceObjectAddress\",\"/\"]},}},\n {\n        \"$project\": {\n            \"_id\": 1,\n            \"description\": 1,\n            \"metric\": \"$description\",\n            \"protocolSourceObjectAddressBAK\": 1,\n            \"tag\": 1,\n            \"ungroupedDescription\": 1,\n            \"alarmed\": 1,\n            \"alarmState\": 1,\n            \"alarmRange\": 1,\n            \"invalid\": 1,\n            \"timeTag\": 1,\n            \"timeTagAtSource\": 1,\n            \"code\": \"$location.properties.code\",\n            \"connection\": \"$location.properties.connexion\",\n            \"lines\": \"$location.properties.ligne\",\n            \"longitude\": { \"$arrayElemAt\": [\"$location.geometry.coordinates\", 0] },\n            \"latitude\": { \"$arrayElemAt\": [\"$location.geometry.coordinates\", 1] },\n            \"location\": 1,\n            \"status\": \"$${view_status}\",\n//            \"value\": {$toInt: \"$${view_status}\"},\n\"value\": {$cond: [{$eq: [\"$timeTag\", null]}, null, {$toInt: \"$${view_status}\"}]},\n//address: 1,\nl1: {$arrayElemAt: [\"$address\", 1]},\nl2: {$arrayElemAt: [\"$address\", 2]},\nl3: {$arrayElemAt: [\"$address\", 3]},\nl4: {$arrayElemAt: [\"$address\", 4]},\nl5: {$arrayElemAt: [\"$address\", 5]},\n\n        }\n    }\n])",
     "type": "table"
    },
    {
     "target": "db.realtimeData.aggregate([\n{\n  $match: {\n    $and: [\n      {protocolSourceConnectionNumber: $protocolSourceConnectionNumber},\n      {tag: /^[^\\/]+(\\/[^\\/]+){${depth}}$/},\n      {tag: /^[^\\/]+(\\/[^\\/]+){4}$/}, // !!!!!!!!!!!!!!!!!!!!!!!!!!\n      {tag: {$regex: ${pathPattern:doublequote}}},\n    ]\n  }\n},\n{\"$sort\": {\"location.properties.code\": 1}},\n{$addFields: {address: {$split: [\"$protocolSourceObjectAddress\",\"/\"]},}},\n {\n        \"$project\": {\n            \"_id\": 1,\n            \"description\": 1,\n            \"metric\": \"$description\",\n            \"protocolSourceObjectAddressBAK\": 1,\n            \"tag\": 1,\n            \"ungroupedDescription\": 1,\n            \"alarmed\": 1,\n            \"alarmState\": 1,\n            \"alarmRange\": 1,\n            \"invalid\": 1,\n            \"timeTag\": 1,\n            \"timeTagAtSource\": 1,\n            \"code\": \"$location.properties.code\",\n            \"connection\": \"$location.properties.connexion\",\n            \"lines\": \"$location.properties.ligne\",\n            \"longitude\": { \"$arrayElemAt\": [\"$location.geometry.coordinates\", 0] },\n            \"latitude\": { \"$arrayElemAt\": [\"$location.geometry.coordinates\", 1] },\n            \"location\": 1,\n            \"status\": \"$${view_status}\",\n//            \"value\": {$toInt: \"$${view_status}\"},\n\"value\": {$cond: [{$eq: [\"$timeTag\", null]}, null, {$toInt: \"$${view_status}\"}]},\n//address: 1,\nl1: {$arrayElemAt: [\"$address\", 1]},\nl2: {$arrayElemAt: [\"$address\", 2]},\nl3: {$arrayElemAt: [\"$address\", 3]},\nl4: {$arrayElemAt: [\"$address\", 4]},\nl5: {$arrayElemAt: [\"$address\", 5]},\n\n        }\n    }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Indicateurs ${pathPattern}",
   "type": "stat",
   "gridPos": { "h": 17, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  distinct(tag),\n  count(*) as \"Alarmes en cours\"\nFROM hist_view\nWHERE\n  $__timeFilter(time_tag)\n  AND alarmed = 1\n  -- AND cast(_id as bigint) in (${devices:raw})\n  AND _id IN (\n    select\n      unnest(\n        array [\n          string_to_array(\n            regexp_replace(\n              '${level0:raw},${level1:raw},${level2:raw},${level3:raw},${level4:raw},${level5:raw}', ',+', ',', 'g'\n            ),\n            ','\n          )\n        ]\n      )\n  )\n  AND tag ~ '^[^\\/]+(\\/[^\\/]+){${depth}}$'\n\n\nGROUP BY 1\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  distinct(tag),\n  count(*) as \"nb équipements connectés\"\nFROM hist_view\nWHERE\n  $__timeFilter(time_tag)\n  AND invalid = 0\n  -- AND cast(_id as bigint) in (${devices:raw})\n    AND _id IN (\n    select\n      unnest(\n        array [\n          string_to_array(\n            regexp_replace(\n              '${level0:raw},${level1:raw},${level2:raw},${level3:raw},${level4:raw},${level5:raw}', ',+', ',', 'g'\n            ),\n            ','\n          )\n        ]\n      )\n  )\n  AND tag ~ '^[^\\/]+(\\/[^\\/]+){${depth}}$'\n\nGROUP BY 1\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  distinct(tag),\n  max(value)\nFROM hist_view\nWHERE\n  $__timeFilter(time_tag)\n  AND invalid = 0\n  -- AND cast(_id as bigint) in (${devices:raw})\n    AND _id IN (\n    select\n      unnest(\n        array [\n          string_to_array(\n            regexp_replace(\n              '${level0:raw},${level1:raw},${level2:raw},${level3:raw},${level4:raw},${level5:raw}', ',+', ',', 'g'\n            ),\n            ','\n          )\n        ]\n      )\n  )\n  AND tag ~ '^[^\\/]+(\\/[^\\/]+){${depth}}$'\n\nGROUP BY 1\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "MESSAGES",
   "type": "alertlist",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_tag AS \"time\",\n  value\nFROM hist\nWHERE\n  $__timeFilter(time_tag)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ratio ${view_status} des ${depth} sur ${pathPattern}",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "db.realtimeData.aggregate([\n{\n  $match: {\n    $and: [\n    { tag: { $regex: \"${pathPattern}\" } },\n    { tag: { $regex: /^[^\\/]+(\\/[^\\/]+){${depth}}$/ } },\n    ]\n  }\n},\n{\n  $project: {\n    _id: 0,\n    metric: \"$description\",\n    \"${view_status}\": { $toInt: \"$${view_status}\" },\n    \"not ${view_status}\": { $toInt: {$not: \"$${view_status}\"} },\n  }\n},\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Défauts ${view_status} des ${depth} sur ${pathPattern}",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  description as metric,\n  -- sum(${view_status}) as \"${view_status}\"\n    sum(${view_status}) as value\nFROM hist_view\nWHERE\n  $__timeFilter(time_tag)\n  --AND CAST(_id as bigint) IN (${devices:raw})\n  AND tag LIKE '%${pathPattern:raw}%' \n  AND regexp_match(tag, '^[^\\/]+(\\/[^\\/]+){${depth}}$') IS NOT NULL\nGROUP BY description\nORDER BY 2 desc,1"
    }
   ]
  },
  {
   "title": "les ${depth} de ${pathPattern}",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "target": "db.realtimeData.aggregate([\n{$addFields: {deeper: {$add: [${depth}, 1] }}},\n{\n$match:{\n\n  protocolSourceConnectionNumber: ${protocolSourceConnectionNumber},\n  $and:[\n    { tag: /^[^\\/]+(\\/[^\\/]+){${depth}}$/},\n//    { tag: /^[^\\/]+(\\/[^\\/]+){2}$/},\n    { tag: { $regex: ${pathPattern:doublequote} }},\n  ],\n  timeTag: {$ne: 0}\n},\n},\n{\n$sort: {\"location.properties.code\": 1}\n},\n{\n$project: {\n  value: {$toInt: \"1\"}, // constant bar height\n  metric: \"$$ROOT.description\",\n  _id: 0,\ntag:1,\n//  color: \"$$view_status\"\n  color: {$cond: [{$eq: [\"$timeTag\", null]}, null, {$toInt: \"$$view_status\"}]}\n}\n}, \n\n])",
     "type": "table"
    }
   ]
  }
 ]
}